# -*- coding: utf-8 -*-
"""Titanic_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qsaDgY18wvAunGtY8WOnVn3LPVYuLQdj
"""

from google.colab import files
uploaded = files.upload()  # Choose titanic.zip

import zipfile

with zipfile.ZipFile("titanic.zip", 'r') as zip_ref:
    print(zip_ref.namelist())  # Shows files inside

with zipfile.ZipFile("titanic.zip", 'r') as zip_ref:
    zip_ref.extractall()  # Extracts to current folder

import pandas as pd
df = pd.read_csv("train.csv")  # Or use the name you saw in step 2
df.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10,6)

df = pd.read_csv("train.csv")  # or use the URL method

df.head()
df.shape
df.info()
df.describe()
df.isnull().sum()

df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.drop(columns=['Cabin'], inplace=True)

sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

sns.histplot(df['Age'], bins=30, kde=True)
plt.title("Age Distribution")
plt.show()

sns.countplot(x='Pclass', data=df)
plt.title("Passenger Class Distribution")
plt.show()

sns.countplot(x='Sex', data=df)
plt.title("Gender Distribution")
plt.show()

sns.barplot(x='Sex', y='Survived', data=df)
plt.title("Gender vs Survival Rate")
plt.show()

sns.barplot(x='Pclass', y='Survived', data=df)
plt.title("Class vs Survival Rate")
plt.show()

sns.boxplot(x='Survived', y='Age', data=df)
plt.title("Age vs Survival")
plt.show()

# Correlation Heatmap
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Pairplot
sns.pairplot(df[['Survived', 'Age', 'Fare', 'Pclass']], hue='Survived')
plt.show()